name: Auto Merge and Delete Branch

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check PR approvals
      id: approval
      run: |
        APPROVALS=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '[.reviews[].state] | map(select(. == "APPROVED")) | length')
        echo "Number of approvals: $APPROVALS"
        echo "::set-output name=approvals::$APPROVALS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge PR if approved
      if: steps.approval.outputs.approvals >= 1
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch --repo ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
